/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vending_machine;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2021-02-24")
public enum BeverageType implements org.apache.thrift.TEnum {
  HOT(0),
  COLD(1);

  private final int value;

  private BeverageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static BeverageType findByValue(int value) { 
    switch (value) {
      case 0:
        return HOT;
      case 1:
        return COLD;
      default:
        return null;
    }
  }
}
