/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vending_machine;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2021-02-24")
public enum ErrorCode implements org.apache.thrift.TEnum {
  SE_CONNPOOL_TIMEOUT(0),
  SE_THRIFT_CONN_ERROR(1),
  SE_UNAUTHORIZED(2),
  SE_MEMCACHED_ERROR(3),
  SE_MONGODB_ERROR(4),
  SE_REDIS_ERROR(5),
  SE_THRIFT_HANDLER_ERROR(6),
  SE_RABBITMQ_CONN_ERROR(7);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return SE_CONNPOOL_TIMEOUT;
      case 1:
        return SE_THRIFT_CONN_ERROR;
      case 2:
        return SE_UNAUTHORIZED;
      case 3:
        return SE_MEMCACHED_ERROR;
      case 4:
        return SE_MONGODB_ERROR;
      case 5:
        return SE_REDIS_ERROR;
      case 6:
        return SE_THRIFT_HANDLER_ERROR;
      case 7:
        return SE_RABBITMQ_CONN_ERROR;
      default:
        return null;
    }
  }
}
